<?xml version="1.0"?>
<package format="3">
  <name>urban_road_filter</name>
  <version>0.0.0</version>
  <description>The urban_road_filter package_ROS2_Version</description>

  <maintainer email="barhamfarraj@icloud.com">Barham Farraj</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

</package>
